### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by marceloavf** [oikonomopo/electron-deep-linking-mac-win#1]
First of all thank you for this awesome repo!

I found a bug when you try to open the app when it's already open:

## A Javascript error occurred in the main process
Uncaught Exception:
ReferenceError: win is not defined at Function.app.makeSingleInstance

There is a way to fix it, to say that the app is already open or focus in the opened app ?

**Comment by oikonomopo** [comment]
Mm you are right! I think i haven't pushed a variable name update!:
Try to replace variable name `win` with `mainWindow`!

**Comment by marceloavf** [comment]
It works! Thank you so much.
