### ISSUE TITLE
Not working on chrome 

### ISSUE THREAD

**Issue by Ajeey** [oikonomopo/electron-deep-linking-mac-win#2]
Cloned your repo and created a dist.

I am able to launch the app from safari & firebox by typing `myapp://param` in the url

But when I type the same url in "Chrome", the app is not being launched.

Does this even work in chrome?

**Comment by oikonomopo** [comment]
Yes it was working. I don't remember the version i tried then and i can't test it right now.

**Comment by oikonomopo** [comment]
Reopen based to https://discuss.atom.io/t/enable-deep-linking/27518/6#post_6 . 
Don't have time to check it yet, it seems that with newer version of Chrome we encounter this issue.

**Comment by Ajeey** [comment]
In chrome I made it work by embedding the custom url in a link.
Ex - `<a href="myapp://param">Open app</a>`
