### ISSUE TITLE
How to do it same thing on win-64

### ISSUE THREAD

**Issue by ketanvekaria** [oikonomopo/electron-deep-linking-mac-win#31]
How to do it same thing on win-64

**Comment by ketanvekaria** [comment]
@oikonomopo  will you please help us here?

**Comment by oikonomopo** [comment]
It's the same code for both Windows 32/64 bit!

> [From related docs:](https://www.npmjs.com/package/electron-packager#supported-platforms)
> Electron Packager is known to run on the following host platforms:
> 1. Windows (32/64 bit)
> ...
> 
> It generates executables/bundles for the following target platforms:
> 1. Windows (also known as [win32](https://nodejs.org/api/os.html#os_os_platform), for x86, x86_64, and arm64 architectures)
> ...

`win32` refers Windows platform, not the architecture, so it's used for both Windows 32/64 bit versions
