### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ketanvekariya** [oikonomopo/electron-deep-linking-mac-win#32]
It would be better if we had linux support on same git repository.

**Comment by ketanvekaria** [comment]
@oikonomopo will you please help here

**Comment by KorbsStudio** [comment]
This seems to be working just fine on Linux.
I tested this on Ubuntu 21.04 using Microsoft Edge Dev.

**Comment by oikonomopo** [comment]
It was working as far as I remember.
